### ISSUE TITLE
Privacy Policy?

### ISSUE THREAD

**Issue by i0tman** [deathau/csv-obsidian#6]
I noticed there is not a privacy policy attached to this repository. When looking at the main.ts and I noticed you are importing from several other repositories/projects. What are your security controls and privacy policy? Are there any APIs that pull the data being read or is everything "offline" after the initial install on Obsidian?

**Comment by deathau** [comment]
This is all offline (you could even download it separately and install it offline if you wish).

All this does is parse the CSV and render it out in a table. It does use those third-party libraries to do so, but no information is sent anywhere.

**Comment by i0tman** [comment]
Fantastic, Thank You.
